# 테스트 환경에서 사용하는 설정 파일
# 포트번호 변경
server:
  port: 8090

# 기본 설정
spring:
  application:
    name: sbb

  # MySQL 데이터베이스 설정
  datasource:
    url: jdbc:mariadb://localhost:3306/db01_test?serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: tj01
    password: 1234

  # JPA 환경 설정
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        "[show_sql]": true
        "[format_sql]": true
    defer-datasource-initialization: true

  devtools:
    livereload:
      enabled: true
 
  # SQL 파일 자동 실행
  sql:
    init:
      mode: always